#!/bin/bash
OMPI_COMM_WORLD_NODE_RANK=${OMPI_COMM_WORLD_NODE_RANK:-0}
IP="10.10.1.7"
BASE_PORT=10101
PORT=$(($OMPI_COMM_WORLD_NODE_RANK + $BASE_PORT))
export DELTAFS_MetadataSrvAddrs=$IP:$PORT
numactl --all -C $OMPI_COMM_WORLD_NODE_RANK -- deltafs-srvr -v=1 -logtostderr
