- hosts: 'client'
  become: true
  tasks:
  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
      - gcc
      - g++
      - make
      - autoconf
      - automake
      - libtool
      - pkg-config
      - cmake
      - checkinstall
      - libsnappy-dev
      - liburing2
      - libgflags-dev
      - libgoogle-glog-dev
      - libopenmpi-dev
      - libjson-c-dev
  - name: Copy .deb packages (OFI, mercury, deltafs)
    ansible.builtin.copy:
      src: '{{ item }}'
      dest: '/tmp/'
      mode: 0755
    with_fileglob:
      - './build/*.deb'
  - name: Install .deb packages
    ansible.builtin.shell: |
      sudo dpkg -i /tmp/libfabric*.deb
      sudo dpkg -i /tmp/mercury*.deb
      sudo dpkg -i /tmp/deltafs*.deb
